# Generated by Django 4.2.19 on 2025-02-26 12:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menu_options_menu_level_menu_lft_menu_rght_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('document_path', models.CharField(blank=True, max_length=255, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.application')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.customuser')),
            ],
        ),
    ]
