# Generated by Django 4.2.19 on 2025-02-26 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_tempdocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menupermission',
            options={'verbose_name': 'Menu Permission Assignment', 'verbose_name_plural': 'Menu Permission Assignments'},
        ),
    ]
