# Generated by Django 4.2.19 on 2025-03-02 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_document_documentcategory_documenttype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('document_path', models.CharField(blank=True, max_length=500, null=True)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('API', 'API'), ('BATCH', 'Batch'), ('EMAIL', 'Email'), ('SCANNER', 'Scanner'), ('SFTP', 'SFTP')], default='MANUAL', max_length=10)),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_processing_details', models.JSONField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.application')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.JSONField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.documentstage')),
            ],
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='application',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='client',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='clientapplication',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='clientapplication',
            name='application',
        ),
        migrations.RemoveField(
            model_name='clientapplication',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientoffice',
            name='application',
        ),
        migrations.RemoveField(
            model_name='clientoffice',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientofficer',
            name='application',
        ),
        migrations.RemoveField(
            model_name='clientofficer',
            name='client',
        ),
        migrations.RemoveField(
            model_name='document',
            name='application',
        ),
        migrations.RemoveField(
            model_name='document',
            name='client',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
        migrations.RemoveField(
            model_name='loandocument',
            name='document',
        ),
        migrations.RemoveField(
            model_name='loandocument',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='loandocument',
            name='loan_application',
        ),
        migrations.RemoveField(
            model_name='loandocument',
            name='verified_by',
        ),
        migrations.RemoveField(
            model_name='servicelog',
            name='application',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_short_name',
            new_name='primary_contact_name',
        ),
        migrations.AlterUniqueTogether(
            name='documentcategory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='annual_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.application'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='number_of_employees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='primary_contact_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='primary_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='short_name',
            field=models.CharField(default='test client', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='year_established',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='category_code',
            field=models.CharField(choices=[('identification', 'Identification Documents'), ('income', 'Income Verification'), ('asset', 'Asset Documentation'), ('credit', 'Credit History'), ('property', 'Property Information'), ('debt', 'Debt Obligations'), ('down_payment', 'Down Payment Verification'), ('loan_specific', 'Loan-Specific Requirements'), ('additional', 'Additional Documentation'), ('untagged', 'Untagged')], default='identification', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='applicant_name',
            field=models.CharField(default='Aniruddha', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='case_readiness',
            field=models.IntegerField(default=0, help_text='Percentage completion of required documents'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='credit_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='document_index',
            field=models.IntegerField(default=0, help_text='Percentage of document review completion'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='dti_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='fein',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='legal_name',
            field=models.CharField(default='test_client', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_types', to='menu.documentcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='documentcategory',
            unique_together={('application', 'category_code')},
        ),
        migrations.DeleteModel(
            name='APIRequest',
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='ClientApplication',
        ),
        migrations.DeleteModel(
            name='ClientOffice',
        ),
        migrations.DeleteModel(
            name='ClientOfficer',
        ),
        migrations.DeleteModel(
            name='LoanDocument',
        ),
        migrations.DeleteModel(
            name='ServiceLog',
        ),
        migrations.AddField(
            model_name='documentstage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.documentcategory'),
        ),
        migrations.AddField(
            model_name='documentstage',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.client'),
        ),
        migrations.AddField(
            model_name='documentstage',
            name='loan_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.loanapplication'),
        ),
        migrations.AddField(
            model_name='documentstage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentaccesslog',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.documentstage'),
        ),
        migrations.AlterField(
            model_name='documentprocessinglog',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.documentstage'),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
