# Generated by Django 4.2.19 on 2025-03-02 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_documentstage_documentversion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.application'),
        ),
    ]
