# Generated by Django 4.2.19 on 2025-03-02 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_loanapplication_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='application',
            field=models.ForeignKey(default='16fc6cb00c71447e8efa3120f230bc61', on_delete=django.db.models.deletion.CASCADE, to='menu.application'),
            preserve_default=False,
        ),
    ]
