# Generated by Django 4.2.19 on 2025-03-02 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_loanapplication_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.application'),
        ),
    ]
