# Generated by Django 4.2.19 on 2025-03-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_client_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
